# Generated by Django 4.1.3 on 2022-12-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='newsstory',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
